// RESTAURANTS TYPES
export const FETCHING_RESTAURANTS_REQUEST = 'FETCHING_RESTAURANTS_REQUEST';
export const FETCHING_RESTAURANTS_SUCCESS = 'FETCHING_RESTAURANTS_SUCCESS';
export const FETCHING_RESTAURANTS_FAILURE = 'FETCHING_RESTAURANTS_FAILURE';

// USER TYPES
export const REGISTER_USER = 'REGISTER_USER';
export const GET_USER_BY_EMAIL = 'GET_REGISTER_USER_BY_EMAIL';
export const GET_USER_HISTORY = 'FETCHING_RESTAURANTS_FAILURE';
